[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@matterlabs/=lib/era-contracts/system-contracts/contracts/"
]
solc = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
zksync_testnet = "${ZKSYNC_TESTNET_URL}"
zksync_mainnet = "${ZKSYNC_MAINNET_URL}"
